edition = "2018"
empty_item_single_line = false
indent_style = "Block"
tab_spaces = 4
max_width = 100
comment_width = 80
wrap_comments = true
normalize_comments = true
format_code_in_doc_comments = true
format_strings = true
reorder_modules = true
reorder_imports = true
imports_layout = "HorizontalVertical"
merge_imports = true
newline_style = "Unix"
overflow_delimited_expr = true
remove_nested_parens = true
where_single_line = true