[package]
authors = ["Steve Pryde <spryde81@gmail.com>"]
edition = "2024"
name = "scores-server"
version = "0.1.0"

[dependencies]
axum = "0.8"
chrono = { version = "0.4", features = ["serde"] }
rustrict = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
